#version 450

layout(local_size_x = 64) in;

layout(set = 0, binding = 0) buffer restrict readonly Palet {
    uint palet[];
};

layout(set = 0, binding = 1) buffer restrict readonly TileSet {
    uint tileSet[];
};

layout(set = 0, binding = 2, rgba8ui) uniform uimage2D renderTexture;



void main() {
    // in uvec3 gl_GlobalInvocationID;
    uint tile_id = gl_WorkGroupID.x;
    uint index = gl_LocalInvocationID.x;

    uint x = index % 8;
    uint y = index / 8 + (tile_id * 8 /*gl_WorkGroupSize.x*/);

    imageStore(renderTexture, ivec2(x, y),
               uvec4(palet[tileSet[index + tile_id * gl_WorkGroupSize.x]]));

    // imageStore(renderTexture, ivec2(x, y),
    //     uvec4(palet[x%2]));

    // imageStore(renderTexture, ivec2(x, y),
    //             uvec4(x, y, index, tile_id));
    // imageStore(renderTexture, ivec2(x, y),
    //             uvec4(0, x, y, index));
    
}